name: Build-Test-Fmt

on:
  [push]

jobs:
  build-test-fmt:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest, macos-14]
    runs-on: ${{ matrix.os }}
    
    steps:
    - uses: actions/checkout@v3

    - run: rustup show

    - uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build
      
    - name: Test
      run: cargo test
